DataFormatException: Added new unchecked exception class to replace java.util.zip.DataFormatException. FrameDecoder, FlacDecoder, DecodeFlacToWav: Updated code to use the new unchecked exception class, thus reducing syntactic noise.